title: "COMPASSLAB"
baseURL: "https://www.example.com/"
languageCode: "en-us"
theme: compasslab-theme

summaryLength: 20

params:
  title: "COMPASSLAB"
  description: "The COMPASS LAB is a computer architecture research group in the Department of Electrical and Computer Engineering at SKKU."
  images: 
    - "images/hero-image.png"

  logo: "images/lab/lab-logo-small.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "2066, Seobu-ro, Jangan-gu, Suwon-si, Gyeonggi-do, Republic of Korea Sungkyunkwan University Semiconductor Building Room #400526"

  contact:
    - "seokin@skku.edu"
    - "+82-31-299-4915"

  copyright: "Â© 2024 COMPASSLAB All Rights Reserved"

  customCss: ["css/hovering.css"]

  path_prefix: /compasslab
  
  pubClasses:
    ACC: /subjects/accelerator
    CA:  /subjects/computer_architecture
    MS:  /subjects/memory_system
    NDP: /subjects/near_data_processing
    OS:  /subjects/operating_systems

menus:
  main:
    - name: "Home"
      url: /
      weight: 1
    
#    - name: "About"
#      url: "/about"
#      weight: 2

    - name: "News"
      url: "/news"
      weight: 3

    - name: "Members"
      url: "/members"
      weight: 4

    - name: "Researchs"
      url: "/subjects"
      weight: 5

    - name: "Projects"
      url: "/projects"
      weight: 6

    - name: "Publications"
      url: "/publications"
      weight: 7

    - name: "Schedule"
      url: "/schedule"
      weight: 8

    - name: "Memories"
      url: "/memories"
      weight: 9

taxonomies:
  series: "series"
  tags: "tags"
